contacts added
Makoto-kino14/ice-cream-html-css-project2 pull request #3
Opened 2022-07-09 19:30 UTC by Plov3

2022-07-10 15:11 UTC, Makoto-kino14 requested changes

2022-07-10 15:11 UTC, Makoto-kino14 commented on src/partials/contacts.html
> +                <h4 class="contacts__list-header">Monday - Friday</h4>
<!--// между Saturday-Sunday и часами работы нет margin-bottom. Снять класс-->

2022-07-10 15:11 UTC, Makoto-kino14 commented on src/sass/components/_modal-btn.scss
>  .modal-btn {
Удали пож-та этот коммит, не вижу изменений. Но надо доработать кнопки (добавить padding; псевдоэлемент after - стрелочка)

2022-07-10 15:11 UTC, Makoto-kino14 commented on src/sass/layouts/_contacts.scss
> +.contacts__list {
// секции contacts надо дать background-color:#FFF5F6;

2022-07-10 15:11 UTC, Makoto-kino14 commented on src/sass/layouts/_contacts.scss
> +.contacts__list-item {
// нет стилей границ

2022-07-10 15:11 UTC, Makoto-kino14 commented on src/sass/layouts/_contacts.scss
> +  padding: 32px 40px;
// padding для верха и низа должен быть равен правому и левому (десктопная версия)

2022-07-10 15:11 UTC, Makoto-kino14 commented on src/sass/layouts/_contacts.scss
> +  padding: 3px 24px;
// padding вверху и внизу задавать не надо

2022-07-10 15:11 UTC, Makoto-kino14 commented on src/sass/layouts/_contacts.scss
> +.contacts__list-description {
// почему то на макете отображен перенос другого слова

2022-07-10 15:11 UTC, Makoto-kino14 commented on src/sass/layouts/_contacts.scss
> +.contacts__working-hours {
// убери margin-bottom с last-child (вторые часы работы на макете)

2022-07-10 15:11 UTC, Makoto-kino14 commented on src/sass/layouts/_contacts.scss
> +  color: #ffa5ba;
// вставить цвет - переменную

2022-07-10 15:11 UTC, Makoto-kino14 commented on src/sass/layouts/_contacts.scss
> +.contacts__list-wrap {
// padding и margin снизу для десктопа и планшета - 32px

2022-07-10 15:11 UTC, Makoto-kino14 commented on src/sass/layouts/_contacts.scss
> +  color: #d41443;
// вставить цвет - переменную

2022-07-10 18:29 UTC, Plov3 commented on src/sass/components/_modal-btn.scss
>  .modal-btn {
да, все один в один. не знаю как это убрать. возможно это из-за того, что я изменил там что-то. Потом решил не трогать, чтобы не испортить и отменил действия.

2022-07-10 18:35 UTC, Plov3 commented on src/sass/layouts/_contacts.scss
> +.contacts__list-item {
не понял каких границ нет(

2022-07-10 18:46 UTC, Plov3 commented on src/sass/layouts/_contacts.scss
> +.contacts__list-description {
на макете зачем-то ширина поля для текста ограничена. исправил

2022-07-11 08:52 UTC, Makoto-kino14 commented on src/sass/components/_modal-btn.scss
>  .modal-btn {
Удалила файл в ветке feature/contacts

2022-07-11 08:59 UTC, Makoto-kino14 requested changes
![image](https://user-images.githubusercontent.com/103353487/178227554-3012eb8e-056a-4afa-bf1e-cc051b3b1238.png)
 Расул, что то с 3ей лишкой по ширине (она больше остальных при ширине экрана 1200-1280 px). По кнопкам еще надо доработать

2022-07-11 08:59 UTC, Makoto-kino14 commented on src/sass/layouts/_contacts.scss
> +.contacts__list-description {
Расул, проверь третью ли-шку в ul contacts__list. При ширине от 1200 до 1279 px она шире других

2022-07-11 08:59 UTC, Makoto-kino14 commented on src/partials/contacts.html
> +    <ul class="contacts__btn list">
Кнопки отображаются только при ширине 1200 px

2022-07-11 13:29 UTC, closed without merging