feature/gallery
Makoto-kino14/ice-cream-html-css-project2 pull request #8
Opened 2022-07-11 14:15 UTC by IraRogova

Добавила картинки, html и css

2022-07-11 18:04 UTC, Makoto-kino14 requested changes
Ирин, положите пож-та изображения в существующие папки в структуре проекта: desktop - desk-gallery; tablet - tab-gallery; mobile - mob-gallery.
Как вернете на меня - сразу объединю обе ветки и проверю все. Если будут правки - отпишу, внесем их через bugfix

2022-07-12 06:33 UTC, Makoto-kino14 requested changes
![image](https://user-images.githubusercontent.com/103353487/178424125-25659998-b3bb-47a5-ae67-6af4950f689d.png)

2022-07-12 06:33 UTC, Makoto-kino14 commented on src/sass/layouts/_gallery.scss
> +.gallery__row {
При ширине вьюпорта 1280 и больше - перепроверьте ширину контейнера, в который вписано изображение (flex выдает больше по ширине)

2022-07-12 06:49 UTC, IraRogova commented
Мадина, объедините так, поправлю после комментария ментора.

2022-07-12 07:18 UTC, Makoto-kino14 approved these changes

2022-07-12 07:18 UTC, merged