feature/about
Makoto-kino14/ice-cream-html-css-project2 pull request #9
Opened 2022-07-11 14:44 UTC by 0runley

сверстанная секция about

2022-07-11 17:58 UTC, Makoto-kino14 requested changes
Елнур, внеси пож-та правки: 
1) Удалить src-partial-example
2) Удалить images-logo.png
[оба файла удалены на ветке main, возможно ты не сделал fetch]
3) Переименовать картинки "about_bg_part_1/2**_desk**@png , чтобы было понятно для какого устройства
4) Положить изображения в папки в основной структуре проекта (свои не создавать) - _images_desktop_desk-about_ и так же для tab и mob
5) Вернуть свойство img в base

2022-07-11 17:58 UTC, Makoto-kino14 commented on src/sass/base/_base.scss
> +    min-width: 100%;
надо отменить эту правку. При max-width изображение растягивается по мере увеличения контейнера, и если контейнер станет больше изображения - картинка не будет больше растягиваться. При min-width 100%, если контейнер будет меньше картинки, она туда не поместится и появится скролл-бар

2022-07-12 09:25 UTC, 0runley commented on src/sass/base/_base.scss
> +    min-width: 100%;
исправлено

2022-07-12 09:31 UTC, 0runley commented on src/sass/base/_base.scss
> +    min-width: 100%;
+

2022-07-12 09:50 UTC, Makoto-kino14 approved these changes
Пож-та, доделай позже бэкграунд с молоком (чтобы прижимался к краям)

2022-07-12 09:50 UTC, merged